@rootURL = http://localhost:5126

GET {{rootURL}}/api/view/records
Accept: application/json

###
GET {{rootURL}}/api/view/loadData
Accept: application/json

###
GET {{rootURL}}/api/view/employeeTools
Accept: application/json

###
PUT {{rootURL}}/api/view/checkIn/4
Accept: application/json