@rootURL = http://localhost:5126

GET {{rootURL}}/api/view/records
Accept: application/json

###
GET {{rootURL}}/api/view/loadData
Accept: application/json

###
GET {{rootURL}}/api/view/employeeTools
Accept: application/json

###
PUT {{rootURL}}/api/view/checkIn/30
Accept: application/json

###
POST {{rootURL}}/api/view/checkOut/1
Content-Type: application/json
  {
  "dateCheckedOut": "2026-01-01",
  "dateCheckedIn": null,
  "toolId": 1,
  "employeeId": 3
}